///////////////////////////////////////////////////////////////////////////////
//  File generated by HDevelop for HALCON/C++ Version 10.0
///////////////////////////////////////////////////////////////////////////////



#include "HalconCpp.h"



using namespace Halcon;


#ifndef NO_EXPORT_MAIN
// Main procedure 
void action()
{
  using namespace Halcon;

  // Local iconic variables 
  Hobject  Image, Regions, ConnectedRegions1, Contours3;
  Hobject  SelectedContours, Region, ImageReduced, SelectedContours1;
  Hobject  ObjectSelected, Region2, RegionComplement, Region1;
  Hobject  Contours, ConnectedRegions, SelectedRegions, result;
  Hobject  ObjectSelected1, Contours1;


  // Local control variables 
  HTuple  Number1, Index, Number, Index1;

  read_image(&Image, "D:/halcon_learn/È±ÏÝ/ÕýÃæ/1.png");
  auto_threshold(Image, &Regions, 2);
  connection(Regions, &ConnectedRegions1);
  gen_contour_region_xld(ConnectedRegions1, &Contours3, "border");
  select_contours_xld(Contours3, &SelectedContours, "contour_length", 900, 1200, 
      -0.5, 0.5);
  gen_region_contour_xld(SelectedContours, &Region, "filled");
  reduce_domain(Image, Region, &ImageReduced);

  select_contours_xld(Contours3, &SelectedContours1, "contour_length", 150, 160, 
      -0.5, 0.5);

  count_obj(SelectedContours1, &Number1);
  for (Index=1; Index<=Number1; Index+=1)
  {
    select_obj(SelectedContours1, &ObjectSelected, Index);
    gen_region_contour_xld(ObjectSelected, &Region2, "filled");
    complement(Region2, &RegionComplement);
    reduce_domain(ImageReduced, RegionComplement, &ImageReduced);
  }


  var_threshold(ImageMean, Region, 20, 20, 0.5, 2, 'dark')

  threshold(ImageReduced, &Region1, 70, 98);
  gen_contour_region_xld(Region1, &Contours, "border");

  connection(Region1, &ConnectedRegions);

  select_shape(ConnectedRegions, &SelectedRegions, "area", "and", 100, 1000);
  count_obj(SelectedRegions, &Number);
  gen_empty_obj(&result);
  for (Index1=1; Index1<=Number; Index1+=1)
  {
    select_obj(SelectedRegions, &ObjectSelected1, Index1);
    gen_contour_region_xld(ObjectSelected1, &Contours1, "border");

    concat_obj(Contours1, result, &result);


  }
  if (HDevWindowStack::IsOpen())
    disp_obj(Image, HDevWindowStack::GetActive());
  if (HDevWindowStack::IsOpen())
    disp_obj(result, HDevWindowStack::GetActive());




}


#ifndef NO_EXPORT_APP_MAIN
int main(int argc, char *argv[])
{
  using namespace Halcon;
  // Default settings used in HDevelop (can be omitted) 
  set_system("do_low_error","false");
  action();
  return 0;
}
#endif


#endif


