///////////////////////////////////////////////////////////////////////////////
//  File generated by HDevelop for HALCON/C++ Version 10.0
///////////////////////////////////////////////////////////////////////////////



#include "HalconCpp.h"



using namespace Halcon;


#ifndef NO_EXPORT_MAIN
// Main procedure 
void action()
{
  using namespace Halcon;

  // Local iconic variables 
  Hobject  Image, ROI_0, ImageReduced, Region, RegionComplement;
  Hobject  ImageReduced1, Region1, ConnectedRegions, SelectedRegions;
  Hobject  result, ObjectSelected1, RegionDilation, Contours;


  // Local control variables 
  HTuple  Mean, Deviation, AbsoluteHisto, RelativeHisto;
  HTuple  AbsoluteHisto1, RelativeHisto1, MinThresh, MaxThresh;
  HTuple  Number, Index, Area, Row, Column;

  read_image(&Image, "D:/halcon_learn/»±œ›/≤‡√Ê/5.png");
  dev_open_window_fit_image(Image, 0, 0, -1, -1, WindowHandle)
  gen_rectangle1 (ROI_0, 260.365, 266.89, 429.872, 328.675)

  gen_rectangle2(&ROI_0, 369.695, 294.935, HTuple(1.3813).Rad(), 37.0332, 82.0113);
  reduce_domain(Image, ROI_0, &ImageReduced);
  intensity(ImageReduced, ImageReduced, &Mean, &Deviation);
  gray_histo(ImageReduced, ImageReduced, &AbsoluteHisto, &RelativeHisto);
  fast_threshold(ImageReduced, &Region, Mean, Mean+Deviation, 20);
  complement(Region, &RegionComplement);
  reduce_domain(ImageReduced, RegionComplement, &ImageReduced1);
  gray_histo(RegionComplement, ImageReduced1, &AbsoluteHisto1, &RelativeHisto1);
  histo_to_thresh(RelativeHisto1, 2, &MinThresh, &MaxThresh);
  threshold(ImageReduced1, &Region1, 40, 60);

  connection(Region1, &ConnectedRegions);
  select_shape(ConnectedRegions, &SelectedRegions, "area", "and", 30, 40);

  count_obj(SelectedRegions, &Number);
  gen_empty_region(&result);
  for (Index=1; Index<=Number; Index+=1)
  {
    select_obj(SelectedRegions, &ObjectSelected1, Index);
    area_center(ObjectSelected1, &Area, &Row, &Column);
    dilation1(ObjectSelected1, ObjectSelected1, &RegionDilation, 1);
    gen_contour_region_xld(RegionDilation, &Contours, "border");


    concat_obj(Contours, result, &result);
  }
  if (HDevWindowStack::IsOpen())
    clear_window(HDevWindowStack::GetActive());
  if (HDevWindowStack::IsOpen())
    disp_obj(Image, HDevWindowStack::GetActive());
  if (HDevWindowStack::IsOpen())
    disp_obj(result, HDevWindowStack::GetActive());



}


#ifndef NO_EXPORT_APP_MAIN
int main(int argc, char *argv[])
{
  using namespace Halcon;
  // Default settings used in HDevelop (can be omitted) 
  set_system("do_low_error","false");
  action();
  return 0;
}
#endif


#endif


