//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 10.0
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !NO_EXPORT_APP_MAIN
  public HDevelopExport()
  {
    // Default settings used in HDevelop 
    HOperatorSet.SetSystem("do_low_error", "false");
    action();
  }
#endif

  // Main procedure 
  private void action()
  {

    // Local iconic variables 

    HObject ho_Image;

    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);

    ho_Image.Dispose();
    HOperatorSet.GenImage1(out ho_Image, "byte", 512, 512, "");
    ho_Image.Dispose();

  }


}
#if !NO_EXPORT_APP_MAIN
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

