///////////////////////////////////////////////////////////////////////////////
//  File generated by HDevelop for HALCON/C++ Version 10.0
///////////////////////////////////////////////////////////////////////////////



#include "HalconCpp.h"



using namespace Halcon;


#ifndef NO_EXPORT_MAIN
// Main procedure 
void action()
{
  using namespace Halcon;

  // Local iconic variables 
  Hobject  Image, Image1, Image2, Image3;


  // Local control variables 
  HTuple  PreviousPlotMode, ShowCoordinates, Step;
  HTuple  Button, ButtonDown, Row, Column, mode, lastRow;
  HTuple  lastCol;

  read_image(&Image, "D:/gray.tif");
  decompose3(Image, &Image1, &Image2, &Image3);
  get_paint(3600, &PreviousPlotMode);

  set_window_param(3600, "plot_quality", "best");
  set_window_param(3600, "display_grid", "false");


  ShowCoordinates = "false";

  Step = "*";


  Step = 1;

  set_paint(3600, ((HTuple("3d_plot").Append("texture")).Concat(Step)).Concat("auto"));

  if (HDevWindowStack::IsOpen())
    set_paint(HDevWindowStack::GetActive(),"3d_plot");
  set_window_param(3600, "interactive_plot", "true");
  set_colored(3600, 12);
  Button = HTuple();
  ButtonDown = 0;
  while (0 != 1)
  {
    set_check("~give_error");
    get_mposition_sub_pix(3600, &Row, &Column, &Button);

    set_check("give_error");
    if (0 != (Button==HTuple()))
    {
      Button = 0;
    }
    if (0 != (ButtonDown.And(Button==0)))
    {
      ButtonDown = 0;
    }
    if (0 != (HTuple(Button==0).Not()))
    {
      if (0 != ButtonDown)
      {
        if (0 != (Button==1))
        {
          mode = "rotate";
        }
        if (0 != (Button==4))
        {
          mode = "scale";
        }
        if (0 != (Button==5))
        {
          mode = "move";
        }
        update_window_pose(3600, lastRow, lastCol, Row, Column, mode);
      }
      else
      {
        if (0 != (Button==2))
        {
          break;
        }
        ButtonDown = 1;
      }
      lastCol = Column;
      lastRow = Row;
    }
    //disp_image can not be used because it discards all channels but
    //the first, hence the texture mode would not work.
    disp_obj(Image, 3600);
  }
}


#ifndef NO_EXPORT_APP_MAIN
int main(int argc, char *argv[])
{
  using namespace Halcon;
  // Default settings used in HDevelop (can be omitted) 
  set_system("do_low_error","false");
  action();
  return 0;
}
#endif


#endif


