///////////////////////////////////////////////////////////////////////////////
//  File generated by HDevelop for HALCON/C++ Version 10.0
///////////////////////////////////////////////////////////////////////////////



#include "HalconCpp.h"



using namespace Halcon;


#ifndef NO_EXPORT_MAIN
// Main procedure 
void action()
{
  using namespace Halcon;

  // Local iconic variables 
  Hobject  Image, Rectangle, ImageReduced;


  // Local control variables 
  HTuple  Width, Height, Min, Max, Range, Rows;
  HTuple  Columns, Grayval, Indices, Max2, String, s, Result;
  HTuple  Number, Min1, Indices1;

  read_image(&Image, "fabrik");
  gen_rectangle1(&Rectangle, 129, 189, 321, 389);
  reduce_domain(Image, Rectangle, &ImageReduced);
  get_image_size(ImageReduced, &Width, &Height);
  min_max_gray(ImageReduced, Image, 0, &Min, &Max, &Range);
  get_region_points(ImageReduced, &Rows, &Columns);
  get_grayval(ImageReduced, Rows, Columns, &Grayval);
  tuple_find(Grayval, 0, &Indices);
  tuple_max(Grayval, &Max2);
  tuple_string(Grayval, "d", &String);
  tuple_string(Max2, "d", &s);
  tuple_regexp_replace(String, "^0", s, &Result);
  tuple_number(Result, &Number);
  tuple_min(Number, &Min1);
  tuple_find(Number, Min1, &Indices1);

}


#ifndef NO_EXPORT_APP_MAIN
int main(int argc, char *argv[])
{
  using namespace Halcon;
  // Default settings used in HDevelop (can be omitted) 
  set_system("do_low_error","false");
  action();
  return 0;
}
#endif


#endif


